version: "3.9"

services:
  wol-dashboard:
    build:
      context: .
      args:
        - HTTP_PROXY
        - HTTPS_PROXY
        - NO_PROXY
    image: wol-dashboard:latest
    container_name: wol-dashboard
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: 10.21.34.240   # freie IP in deinem LAN
    environment:
      - SCAN_INTERVAL=15
      - CONFIG_PATH=/app/config/devices.yaml
      - PORT=8000
    volumes:
      - ./config:/app/config:ro

networks:
  lan:
    driver: macvlan
    driver_opts:
      parent: eth0                 # hier dein Host-Interface einsetzen (z. B. enp3s0)
    ipam:
      config:
        - subnet: 10.21.34.0/24    # dein LAN-Subnetz
          gateway: 10.21.34.254    # dein Gateway
